language: r
warnings_are_errors: false
sudo: required
dist: trusty

r:
 - release
 - devel

after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
   on_success: change
   on_failure: change


