language: r
warnings_are_errors: false
sudo: required

r_packages:
 - covr
 - testthat

after_success: 
 - Rscript -e 'covr::codecov()'

notifications:
  email:
   on_success: change
   on_failure: change



